### ISSUE TITLE
Bug: Zombie Streams after Disconnect

### ISSUE THREAD

**Issue by korncola** [SenexCrenshaw/StreamMaster#83] opened 2023-08-26 15:26 UTC
**Describe the Bug**
If a disconnect/network hickup to the original stream source happens, there are after that two active clients on status page, one of the clients is shown with 0 kbps. After the client has finished watching/recording, the second (old entry) will stay forever in client and the channel is also still active in the upper box of status page. Fail client does not help. Only kill the server helps.
**Stream Master Info**
- 0.2.18.0 (built from source)

**Link to logs (required)**
- repeating logs when stream source not avaliable for some time: [Gist](https://gist.github.com/korncola/a23fa9cfe4417f16ee970fb4fa97ef82)
- not working to fail client logs: [Gist](https://gist.github.com/korncola/2b997f76ddd13c1dd411e753017dc61a)

**Comment by aniel300** [comment] 2023-08-26 19:02
i have seen this but i didnt know this was the cause

**Comment by aniel300** [comment] 2023-09-21 17:07
from time to time i get one of this but am not sure if this is being cause by sm, emby or my provider. here is a screenshot for reference
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/fa3ec9d7-6003-4ed8-8d09-962900967aec)

**Comment by SenexCrenshaw** [comment] 2023-10-31 14:44
fixed in latest

**Closed** 2023-10-31 17:56 UTC
Labels: bug
