### ISSUE TITLE
Bug: All show dates being interpreted as new

### ISSUE THREAD

**Issue by bradmurray** [SenexCrenshaw/StreamMaster#236] opened 2024-06-28 13:20 UTC
**Describe the Bug**
Old shows are getting the description tagged like:
[NEW] Original air date: 12/12/2018

**Stream Master Info**
0.14.6.0

**Comment by infosecmatters2021** [comment] 2024-09-26 19:27
@SenexCrenshaw @bradmurray 
Root cause:
- appears to be adding <date>19700101</date> to each line in the EPG xml file.
Solution:
- This date is not in the original source EPG material. Streammaster is adding it for an unknown reason. Please remove the addition of this date field if it does not exist in the source file.

**Comment by SenexCrenshaw** [comment] 2024-10-31 13:37
fixed in latest

**Closed by SenexCrenshaw** 2024-10-31 13:37 UTC
Labels: bug
